# Generated by Django 3.2.3 on 2023-01-12 18:15

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20230112_2307'),
    ]

    operations = [
        migrations.CreateModel(
            name='temp_verification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(max_length=10)),
                ('section', models.CharField(max_length=10)),
                ('Year', models.DateField(default=datetime.datetime.now)),
                ('roll_number', models.IntegerField(blank=True, null=True)),
                ('department', models.CharField(blank=True, max_length=500, null=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account.college')),
            ],
        ),
    ]
