# Generated by Django 3.2.3 on 2023-01-13 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_temp_verification_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='temp_verification',
            name='is_varified',
            field=models.BooleanField(default=False),
        ),
    ]
