# Generated by Django 3.2.3 on 2023-01-13 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_temp_verification_is_varified'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(default='asd@gmail.com', max_length=254),
            preserve_default=False,
        ),
    ]
