# Generated by Django 3.2.3 on 2023-01-22 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_profile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='temp_verification',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
