# Generated by Django 3.2.3 on 2023-01-22 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_temp_verification_is_rejected'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profile_status',
            new_name='is_verified',
        ),
        migrations.AddField(
            model_name='profile',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
