# Generated by Django 4.1.2 on 2022-11-23 21:47

import courses.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Assignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("max_grades", models.PositiveIntegerField()),
                ("deadline", models.DateTimeField()),
                ("info", models.CharField(blank=True, max_length=500, null=True)),
                ("link", models.URLField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("released", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="College",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("category", models.CharField(max_length=200)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="courseImg"),
                ),
                ("course_price", models.CharField(default="FREE", max_length=100)),
                (
                    "course_level",
                    models.CharField(
                        choices=[
                            ("Beginner", "Beginner"),
                            ("Intermediate", "Intermediate"),
                            ("Advanced", "Advanced"),
                        ],
                        default="Beginner",
                        max_length=20,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_courses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="courseTopic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("info", models.CharField(blank=True, max_length=500, null=True)),
                ("link", models.URLField(blank=True, null=True)),
                ("released", models.BooleanField(default=False)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="courseTopics",
                        to="courses.course",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="courseUnit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=8)),
                ("is_assignment", models.BooleanField(default=False)),
                (
                    "assignments",
                    models.ManyToManyField(blank=True, to="courses.assignment"),
                ),
                (
                    "course",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="units",
                        to="courses.course",
                    ),
                ),
                (
                    "topics",
                    models.ManyToManyField(blank=True, to="courses.coursetopic"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Files",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document",
                    models.FileField(blank=True, null=True, upload_to="documents"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.IntegerField(default=1)),
                ("title", models.CharField(max_length=200)),
                (
                    "resource",
                    models.FileField(blank=True, null=True, upload_to="resources/"),
                ),
                ("resource_name", models.CharField(default="Resource", max_length=100)),
                (
                    "resource_link",
                    models.URLField(blank=True, max_length=300, null=True),
                ),
                ("isdone", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="myAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "upload",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="documents",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["pdf"]
                            )
                        ],
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now=True)),
                ("done", models.BooleanField(default=False)),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="my_assignments",
                        to="courses.assignment",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="myFiles",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("done", models.BooleanField(default=False)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="courses.files"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bio", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "profile_pic",
                    models.ImageField(blank=True, null=True, upload_to="profile_pics"),
                ),
                ("full_name", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("M", "MALE"), ("F", "FEMALE"), ("O", "OTHER")],
                        max_length=2,
                        null=True,
                    ),
                ),
                ("country", models.CharField(blank=True, max_length=200, null=True)),
                ("state", models.CharField(blank=True, max_length=40, null=True)),
                ("city", models.CharField(blank=True, max_length=40, null=True)),
                ("linkedin", models.URLField(blank=True, null=True)),
                ("github", models.URLField(blank=True, null=True)),
                ("email", models.EmailField(blank=True, max_length=50, null=True)),
                ("ph_num", models.CharField(blank=True, max_length=15, null=True)),
                ("skills", models.CharField(blank=True, max_length=400, null=True)),
                ("languages", models.CharField(blank=True, max_length=400, null=True)),
                (
                    "default_coding_lang",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "resume",
                    models.FileField(
                        blank=True, null=True, upload_to="profile_resumes"
                    ),
                ),
                (
                    "institute_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "institute_location",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "yearOfPassing",
                    models.PositiveIntegerField(
                        blank=True,
                        default=2022,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1980),
                            courses.models.max_value_current_year,
                        ],
                    ),
                ),
                (
                    "current_cgpa",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MaxValueValidator(100),
                            django.core.validators.MinValueValidator(0),
                        ],
                    ),
                ),
                (
                    "out_of",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MaxValueValidator(100),
                            django.core.validators.MinValueValidator(0),
                        ],
                    ),
                ),
                (
                    "workExp",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(50),
                        ],
                    ),
                ),
                ("current_CTC", models.FloatField(blank=True, null=True)),
                ("notice_period", models.IntegerField(blank=True, null=True)),
                (
                    "willing_to_relocate",
                    models.BooleanField(blank=True, default=True, null=True),
                ),
                ("expected_CTC", models.FloatField(blank=True, null=True)),
                (
                    "current_company",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "dream_company",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "designation",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("xp", models.IntegerField(blank=True, default=100, null=True)),
                (
                    "techsnap_cash",
                    models.IntegerField(blank=True, default=999, null=True),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, editable=False, max_length=200, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("p", "Principal"),
                            ("t", "Teacher"),
                            ("s", "Student"),
                        ],
                        default="s",
                        max_length=5,
                    ),
                ),
                (
                    "college",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="courses.college",
                    ),
                ),
                (
                    "followers",
                    models.ManyToManyField(
                        blank=True,
                        related_name="followers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "teammates",
                    models.ManyToManyField(
                        blank=True,
                        related_name="teammates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserLessonCompletion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("completed", models.BooleanField(default=False)),
                ("unlocked", models.BooleanField(default=False)),
                ("timer_min_left", models.IntegerField(default=0)),
                ("timer_sec_left", models.IntegerField(default=0)),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="courses.lesson"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="courses.profile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Unit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("brief", models.TextField()),
                ("due", models.DateField(null=True)),
                ("released", models.BooleanField(default=False)),
                ("slug", models.SlugField(max_length=300, null=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="courses.course"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MyUnit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        blank=True,
                        default="unit1",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="units",
                        to="courses.unit",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        default="course1",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="courses",
                        to="courses.course",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="mytopics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("done", models.BooleanField(default=False)),
                (
                    "coursetopic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="courses.coursetopic",
                    ),
                ),
                ("documents", models.ManyToManyField(blank=True, to="courses.myfiles")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MyLesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("isdone", models.BooleanField(default=False)),
                (
                    "lesson",
                    models.ForeignKey(
                        blank=True,
                        default="lesson1",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lessons",
                        to="courses.lesson",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="courses.myunit"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="myCourseUnit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "course_assignments",
                    models.ManyToManyField(blank=True, to="courses.myassignment"),
                ),
                (
                    "coursetopics",
                    models.ManyToManyField(blank=True, to="courses.mytopics"),
                ),
                (
                    "courseunit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="courses.courseunit",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="mycourses",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "courses",
                    models.ManyToManyField(
                        blank=True, related_name="mycourses", to="courses.course"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrolledcourses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LessonFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(blank=True, null=True, upload_to="resources/"),
                ),
                ("isdone", models.BooleanField(default=False)),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="courses.lesson",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="lesson",
            name="unit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lessons",
                to="courses.unit",
            ),
        ),
        migrations.CreateModel(
            name="Groups",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[("d", "Default"), ("c", "Custom")],
                        default="d",
                        max_length=5,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_groups",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("enrolled_courses", models.ManyToManyField(to="courses.course")),
                (
                    "students",
                    models.ManyToManyField(
                        related_name="enrolled_groups", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="grades",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("grades", models.PositiveIntegerField(blank=True, null=True)),
                ("remark", models.CharField(blank=True, max_length=100, null=True)),
                ("is_graded", models.BooleanField(default=False)),
                ("graded_at", models.DateTimeField(auto_now=True)),
                (
                    "myassignment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grades",
                        to="courses.myassignment",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="coursetopic",
            name="documents",
            field=models.ManyToManyField(blank=True, to="courses.files"),
        ),
        migrations.AddField(
            model_name="assignment",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignments",
                to="courses.course",
            ),
        ),
        migrations.AddField(
            model_name="assignment",
            name="documents",
            field=models.ManyToManyField(blank=True, to="courses.files"),
        ),
    ]
