# Generated by Django 4.1.2 on 2022-11-23 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_alter_mylesson_unit"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="myunit",
            name="course",
        ),
    ]
