# Generated by Django 4.0 on 2021-12-17 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('courses', '0002_coursetopic_user_mycourses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursetopic',
            name='done',
        ),
        migrations.RemoveField(
            model_name='coursetopic',
            name='user',
        ),
        migrations.AlterField(
            model_name='mycourses',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='mytopics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('done', models.BooleanField(default=False)),
                ('coursetopic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.coursetopic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
