# Generated by Django 4.1.2 on 2022-11-23 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_remove_myunit_course"),
    ]

    operations = [
        migrations.AddField(
            model_name="myunit",
            name="course",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="courses.course",
            ),
        ),
    ]
