# Generated by Django 4.0 on 2021-12-19 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_remove_coursetopic_done_remove_coursetopic_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycourses',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='mycourses', to='courses.course'),
        ),
        migrations.CreateModel(
            name='courseUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=8)),
                ('topics', models.ManyToManyField(blank=True, to='courses.courseTopic')),
            ],
        ),
    ]
