# Generated by Django 4.0 on 2021-12-19 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('courses', '0004_alter_mycourses_courses_courseunit'),
    ]

    operations = [
        migrations.CreateModel(
            name='myCourseUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coursetopics', models.ManyToManyField(blank=True, to='courses.mytopics')),
                ('courseunit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='courses.courseunit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
