# Generated by Django 3.2.3 on 2022-12-14 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_myunit_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='released',
            field=models.BooleanField(default=False),
        ),
    ]
