# Generated by Django 3.2.3 on 2022-12-19 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_lesson_released'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('p', 'Principal'), ('t', 'Teacher'), ('s', 'Student'), ('m', 'Management')], default='s', max_length=5),
        ),
    ]
