# Generated by Django 3.2.3 on 2022-12-26 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_profile_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mycourses',
            name='courses',
        ),
        migrations.AddField(
            model_name='mycourses',
            name='courses',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='courses', to='courses.course'),
        ),
    ]
