# Generated by Django 4.0 on 2021-12-19 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_courseunit_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseunit',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.course'),
        ),
    ]
