# Generated by Django 4.0 on 2021-12-19 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_alter_courseunit_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycourseunit',
            name='courseunit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.courseunit'),
        ),
    ]
