# Generated by Django 3.2.3 on 2022-12-26 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_alter_mycourses_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='mycourses',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
