# Generated by Django 4.0.1 on 2022-06-16 18:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0010_course_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycourses',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='enrolledcourses', to=settings.AUTH_USER_MODEL),
        ),
    ]
