# Generated by Django 3.2.3 on 2023-01-15 13:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0013_alter_groups_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups',
            name='students',
            field=models.ManyToManyField(related_name='enrolled_groups', to=settings.AUTH_USER_MODEL),
        ),
    ]
