# Generated by Django 4.0.1 on 2022-06-19 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='groups',
            name='name',
            field=models.CharField(default='default', max_length=50),
            preserve_default=False,
        ),
    ]
