# Generated by Django 3.2.3 on 2023-01-19 07:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_alter_groups_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager_notification',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 19, 13, 3, 52, 484919)),
        ),
        migrations.AddField(
            model_name='news_feed',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 19, 13, 3, 52, 484430)),
        ),
    ]
