# Generated by Django 4.0.1 on 2022-06-20 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_groups_enrolled_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursetopic',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='documents'),
        ),
        migrations.AddField(
            model_name='coursetopic',
            name='info',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='coursetopic',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
