# Generated by Django 4.0.1 on 2022-06-20 19:14

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0016_coursetopic_document_coursetopic_info_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('document', models.FileField(blank=True, null=True, upload_to='documents', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('max_grades', models.PositiveIntegerField()),
                ('info', models.CharField(blank=True, max_length=500, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='courses.course')),
            ],
        ),
        migrations.CreateModel(
            name='myAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.FileField(blank=True, null=True, upload_to='documents', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('uploaded_at', models.DateTimeField(auto_now=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_assignments', to='courses.assignment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='grades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grades', models.PositiveIntegerField(blank=True, null=True)),
                ('graded_at', models.DateTimeField(auto_now=True)),
                ('myassignment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='courses.myassignment')),
            ],
        ),
        migrations.AddField(
            model_name='courseunit',
            name='assignments',
            field=models.ManyToManyField(blank=True, to='courses.Assignment'),
        ),
        migrations.AddField(
            model_name='mycourseunit',
            name='course_assignments',
            field=models.ManyToManyField(blank=True, to='courses.myAssignment'),
        ),
    ]
