# Generated by Django 3.2.3 on 2023-01-22 10:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_auto_20230119_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursetopic',
            name='created_by',
            field=models.CharField(choices=[('M', 'Manager'), ('T', 'Teacher')], default='T', max_length=20),
        ),
        migrations.AlterField(
            model_name='manager_notification',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 22, 15, 59, 27, 196188)),
        ),
        migrations.AlterField(
            model_name='news_feed',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 22, 15, 59, 27, 195531)),
        ),
    ]
