# Generated by Django 3.2.3 on 2023-01-22 10:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_auto_20230122_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursetopic',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courseTopics', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='manager_notification',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 22, 16, 12, 55, 439422)),
        ),
        migrations.AlterField(
            model_name='news_feed',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 22, 16, 12, 55, 437973)),
        ),
    ]
