# Generated by Django 4.0 on 2022-06-21 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_courseunit_is_assignment_myassignment_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='grades',
            name='is_graded',
            field=models.BooleanField(default=False),
        ),
    ]
