# Generated by Django 3.2.3 on 2023-01-22 16:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_auto_20230122_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager_notification',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 22, 22, 13, 18, 807888)),
        ),
        migrations.AlterField(
            model_name='news_feed',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 22, 22, 13, 18, 807394)),
        ),
    ]
