# Generated by Django 3.2.3 on 2023-01-22 18:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0019_auto_20230122_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager_notification',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 22, 23, 57, 56, 496764)),
        ),
        migrations.AlterField(
            model_name='news_feed',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 22, 23, 57, 56, 496260)),
        ),
    ]
