# Generated by Django 3.2.3 on 2023-01-23 12:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20230122_2358'),
        ('courses', '0020_auto_20230122_2358'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursetopic',
            name='posted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.profile'),
        ),
        migrations.AlterField(
            model_name='manager_notification',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 23, 17, 51, 24, 10375)),
        ),
        migrations.AlterField(
            model_name='news_feed',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 23, 17, 51, 24, 9774)),
        ),
    ]
