# Generated by Django 4.0.1 on 2022-06-23 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0020_college_alter_profile_college'),
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(blank=True, null=True, upload_to='documents')),
                ('done', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='coursetopic',
            name='document',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='document',
        ),
        migrations.AlterField(
            model_name='profile',
            name='college',
            field=models.CharField(choices=[('abc college', 'abc college'), ('def college', 'def college'), ('ijk college', 'ijk college')], max_length=100),
        ),
        migrations.AddField(
            model_name='coursetopic',
            name='documents',
            field=models.ManyToManyField(blank=True, to='courses.Files'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='document',
            field=models.ManyToManyField(blank=True, to='courses.Files'),
        ),
    ]
