# Generated by Django 4.0.1 on 2022-06-23 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0021_files_remove_coursetopic_document_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='document',
            new_name='documents',
        ),
    ]
