# Generated by Django 3.2.3 on 2023-01-23 12:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0021_auto_20230123_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager_notification',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 23, 18, 10, 59, 262772)),
        ),
        migrations.RemoveField(
            model_name='mycourses',
            name='courses',
        ),
        migrations.AddField(
            model_name='mycourses',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='mycourses', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='news_feed',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 23, 18, 10, 59, 262267)),
        ),
    ]
