# Generated by Django 3.2.3 on 2023-01-23 12:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0022_auto_20230123_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='mycourseunit',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='manager_notification',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 23, 18, 27, 23, 716572)),
        ),
        migrations.AlterField(
            model_name='news_feed',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 23, 18, 27, 23, 716073)),
        ),
    ]
