# Generated by Django 4.0.1 on 2022-06-23 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0022_rename_document_assignment_documents'),
    ]

    operations = [
        migrations.CreateModel(
            name='myFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='documents')),
                ('done', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='files',
            name='done',
        ),
        migrations.AddField(
            model_name='mytopics',
            name='documents',
            field=models.ManyToManyField(blank=True, to='courses.myFiles'),
        ),
    ]
