# Generated by Django 4.0 on 2022-06-24 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0023_myfiles_remove_files_done_mytopics_documents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myfiles',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.files'),
        ),
    ]
