# Generated by Django 4.0.1 on 2022-06-25 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0024_alter_myfiles_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='grades',
            name='remark',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
