# Generated by Django 3.2.3 on 2023-04-25 20:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0025_auto_20230126_2352'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='released',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='manager_eveng',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 26, 1, 33, 11, 515936)),
        ),
        migrations.AlterField(
            model_name='manager_notification',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 26, 1, 33, 11, 513865)),
        ),
        migrations.AlterField(
            model_name='news_feed',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 26, 1, 33, 11, 513174)),
        ),
    ]
