# Generated by Django 4.1.2 on 2022-11-07 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0028_alter_courseunit_course"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="college",
            field=models.CharField(
                choices=[
                    ("abc college", "abc college"),
                    ("def college", "def college"),
                    ("ijk college", "ijk college"),
                    ("Jawaharlal Nehru University", "Jawaharlal Nehru University"),
                ],
                max_length=100,
            ),
        ),
    ]
