# Generated by Django 4.1.2 on 2022-11-09 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0030_remove_profile_college_remove_profile_status_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="is_creator",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="is_hr",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="is_student",
        ),
        migrations.AddField(
            model_name="profile",
            name="college",
            field=models.CharField(
                choices=[
                    ("abc college", "abc college"),
                    ("def college", "def college"),
                    ("ijk college", "ijk college"),
                    ("Jawaharlal Nehru University", "Jawaharlal Nehru University"),
                ],
                default="abc",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="status",
            field=models.CharField(
                choices=[("p", "Principal"), ("t", "Teacher"), ("s", "Student")],
                default="s",
                max_length=5,
            ),
        ),
    ]
