# Generated by Django 4.1.2 on 2022-11-09 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0031_remove_profile_is_creator_remove_profile_is_hr_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="college",
            field=models.CharField(choices=[], default="abc", max_length=100),
        ),
    ]
