# Generated by Django 4.1.2 on 2022-11-09 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0032_alter_profile_college"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="college",
            field=models.CharField(
                choices=[("abc college", "abc college")], default="abc", max_length=100
            ),
        ),
    ]
