# Generated by Django 4.1.2 on 2022-11-13 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0033_alter_profile_college"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="released",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="coursetopic",
            name="released",
            field=models.BooleanField(default=False),
        ),
    ]
