# Generated by Django 4.1.2 on 2022-11-14 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0034_assignment_released_coursetopic_released"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="college",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="courses.college"
            ),
        ),
    ]
