# Generated by Django 4.1.2 on 2022-11-14 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0035_alter_profile_college"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="college",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="courses.college",
            ),
        ),
    ]
